-- V1__initial_schema.sql
CREATE TABLE categoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50 CHAR) NOT NULL
);

CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(200 CHAR) NOT NULL,
    email VARCHAR2(150 CHAR) NOT NULL,
    senha VARCHAR2(255 CHAR) NOT NULL,
    perfil VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT uq_usuario_email UNIQUE (email)
);

CREATE TABLE produto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255 CHAR) NOT NULL,
    descricao VARCHAR2(300 CHAR),
    quantidade NUMBER(10) DEFAULT 0 NOT NULL,
    preco_unitario NUMBER(10,2) NOT NULL,
    id_categoria NUMBER,
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

CREATE TABLE movimentacao_estoque (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(10 CHAR) NOT NULL,
    quantidade NUMBER(10) NOT NULL,
    data_movimentacao TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    produto_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_movimentacao_produto FOREIGN KEY (produto_id) REFERENCES produto(id),
    CONSTRAINT fk_movimentacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT chk_tipo_mov CHECK (tipo IN ('ENTRADA','SAIDA'))
);
